config/routes.rb
Rails.application.routes.draw do
  root 'matches#index'
  resources :matches
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
	belongs_to :home_team, class_name: 'Team', foreign_key: 'home_team_id'
  	belongs_to :away_team, class_name: 'Team', foreign_key: 'away_team_id'
  	validates_presence_of :home_team_id, :away_team_id, :time, :location
	def start_time
		self.time
	end
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :home_matches, class_name: 'Match', foreign_key: 'home_team_id'
  	has_many :away_matches, class_name: 'Match', foreign_key: 'away_team_id'
  	validates_presence_of :name, :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.all
    start_date = params.fetch(:start_date, Date.today).to_date
    @matches_curr_month = Match.where(time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    joined = Match.joins(:home_team, :away_team)
    @favorite_matches = joined.where(home_team: {favorite: true}).or(joined.where(away_team: {favorite: true}))
  end

  # GET /matches/1 or /matches/1.json
  def show
    @match = Match.find(params[:id])
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:home_team_id, :away_team_id, :time, :location,:home_team_score, :away_team_score, :description)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  	@team = Team.find(params[:id])
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  	@team = Team.find(params[:id])
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to teams_url, notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to teams_url, notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
  	@team = Team.find(params[:id])
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name, :city, :description, :favorite)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<%= render "shared/header" %>

<!DOCTYPE html>
<html>
  <head>
    <title>SportsCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <h3>
    <div>
      <%= form.label :home_team_id %><br>
      <%= form.collection_select :home_team_id, Team.order(:name), :id, :name %>
    </div>

    <div>
      <%= form.label :away_team_id %><br>
      <%= form.collection_select :away_team_id, Team.order(:name), :id, :name %>
    </div>

    <div>
      <%= form.label :time %><br>
      <%= form.datetime_local_field :time, :class => 'time_form_field'  %>
    </div>

    <div >
      <%= form.label :location %><br>
      <%= form.text_field :location, :class => 'small_form_field' %>
    </div>

    <div>
      <%= form.label :home_team_score %><br>
      <%= form.number_field :home_team_score, min: 0, :class => 'small_form_field' %>
    </div>

    <div>
      <%= form.label :away_team_score %><br>
      <%= form.number_field :away_team_score, min: 0, :class => 'small_form_field' %>
    </div>

    <div>
      <%= form.label :description %><br>
      <%= form.text_field :description, :class => 'big_form_field' %>
    </div>

    <div>
      <%= form.submit 'SUBMIT', :class => 'button form_button' %>
    </div>
  </h3>
  
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class="container">
    <div class="spacer"></div>
    <div class="form_container">
        <h2>Edit Match</h2>
        <%= render 'matches/form', match: @match %>
    </div>
</div>

app/views/matches/index.html.erb
<div class="container">  
  <div class="spacer"></div>
  <div class="matches_container open_sans_font" style="padding-top: 50px;">
    <div class="top_container">
      <div class="title_container">
        <h1>UPCOMING MATCHES</h1>
      </div>
      <div class="button_container">
        <button class="button open_sans_font">
          <%= link_to 'NEW MATCH', new_match_path %>
        </button>
      </div>
    </div>
  </div>
  <div class="white_background">
    <div class="matches_container open_sans_font">
      <div class="calendar_container">
        <%= month_calendar(events: @matches_curr_month) do |date, matches_curr_month| %>
          <div class="date_text"><%= date.day %></div>
          <% matches_curr_month.each do |matches_curr_month| %>
            <p>
              <%= matches_curr_month.away_team.name %> @ <%= matches_curr_month.home_team.name %>
            </p>
          <% end %>
        <% end %>
      </div>
      <div class="list_container">
        <table style="float: right">
          <thead>
            <tr>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody class="table_content">
            <% @matches.each do |match| %>
              <tr>
                <td class="table_spacing"><p><%= match.away_team.name %> @ <%= match.home_team.name %><p></td>
                <td class="table_spacing"><p><%= match.time %><p></td>
                <td class="edit_link"><p><%= link_to 'Edit', edit_match_path(match) %><p></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="matches_container open_sans_font" style="padding-top: 50px;">
    <div class="top_container">
      <div class="title_container">
        <h1>FAVORITE MATCHES</h1>
      </div>
    </div>
  </div>
  <div class="white_background">
    <div class="matches_container open_sans_font" style="padding-bottom: 50px">
      <div class="calendar_container">
        <%= month_calendar(events: @favorite_matches) do |date, favorite_matches| %>
          <div class="date_text"><%= date.day %></div>
          <% favorite_matches.each do |favorite_matches| %>
            <p>
              <%= favorite_matches.away_team.name %> @ <%= favorite_matches.home_team.name %>
            </p>
          <% end %>
        <% end %>
      </div>
      <div class="list_container">
      </div>
    </div>
  </div>
</div>

app/views/matches/new.html.erb
<div class="container">
    <div class="spacer"></div>
    <div class="form_container">
        <h2>New Match</h2>
        <%= render 'matches/form', match: @match %>
    </div>
</div>

app/views/matches/show.html.erb
<h1> <%= @match.away_team.city %> <%= @match.away_team.name %> @ <%= @match.home_team.city %> <%= @match.home_team.name %> </h1>
<h2> Time: <%= @match.time %> </h2>
<h2> Location: <%= @match.location %> </h2>
<h2> Description: <%= @match.description %> </h2>
<h2> Score: <%= @match.away_team_score %> - <%= @match.home_team_score %> </h2>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/shared/_header.html.erb
<div class="header_container">
    <div style="display: flex; flex-direction: row; width: 90%; margin: auto; align-items: center">
        <div class="header_title">
            <h1 style="color: #ffffff"> BASKETBALL MATCH TRACKER <h1>
        </div>
        <div class="header_link open_sans_font">
            <%= link_to 'Teams', teams_path %>
        </div>
        <div class="header_link open_sans_font">
            <%= link_to 'Matches', matches_path %>
        </div>
    </div>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <h2 class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></h2>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>